### ISSUE TITLE
Provide working example

### ISSUE THREAD

**Issue by dschick** [sflewett/3D_XRMS#1]
Hi @sflewett 

many thanks for putting this up!
Could you please also add a working example as script or jupyter notebook in order to test the formalism?

Best

Daniel

**Comment by dschick** [comment]
Hi @sflewett 

I got the specular reflectivity working, but for the 3D case, there are some Matlab data files missing.

I am closing for now and reopen when approaching the 3D case.

Daniel

**Comment by sflewett** [comment]
Hi Daniel,

I will revise stuff related to this project tomorrow. Off on vacations on
Saturday, so a lot to get sorted before then

Cheers

Sam

**Comment by dschick** [comment]
I think I got the reflectivity now working:
![image](https://github.com/sflewett/3D_XRMS/assets/13797420/2c70a064-ef95-4655-9d65-7cc641458c20)
not too sure if I did it right for the transmission ... in the paper, Stepanov & Sinha mainly refer to thick slabs and multilayers and neglecting the transmission.

**Comment by sflewett** [comment]
That looks great, however for the transmission, you need to look at the
value of the transmitted field in the final layer of the sample

Cheers

Sam

**Comment by dschick** [comment]
I think I did that. Here is what I calculate
```python
R_fields = sim.R_fields
R = np.dot(sim.Wrt[-1], sim.Incident)
T = np.dot(sim.Wtt[-1], sim.Incident) + np.dot(sim.Wrt[-1], R_fields[-1])
Rs[i] = np.real(R[0]*np.conj(R[0]) + R[1]*np.conj(R[1]))
Ts[i] = np.real(T[0]*np.conj(T[0]) + T[1]*np.conj(T[1]))
```

for which I have newly introduced the `Wtt` and `Wrt` attributes of the simulation in order to access these matrices

**Comment by sflewett** [comment]
To get the transmitted field, I would just use the final output from
equation 70, T_fields, or T_fields_linear

Cheers

Sam
