### ISSUE TITLE
What does `Basischange` does?

### ISSUE THREAD

**Issue by dschick** [sflewett/3D_XRMS#2]
Hi @sflewett 

I am further digging through your code, and I could link nearly everything to the equations in the Stepanov paper - thanks for being so close with your name scheme.

There is, however, one part which I could not link from your code to the paper: it is about the `Basischange`:
https://github.com/sflewett/3D_XRMS/blob/4a54ffef5454df8a47fdfeaf26b7916e2e50a1ae/Stepanov_Specular.py#L334-L339

I would guess that this is about switching the polarization basis at each layer depending on a specific criterium.
Is this linked to the three cases given by Eqs. (52-54) in the paper?

**Comment by sflewett** [comment]
Hi Daniel,

Can we zoom chat at 10? Today is My last day of work until August 15, so it
would be good to get things in order.

Cheers

Sam

**Comment by dschick** [comment]
thanks for explaining, that you are changing the polarization basis for all fields within the layers to a linear basis at that point.
this is however not necessary when calculating the total reflectivity of the whole stack - but when looking at the 3D case.

**Comment by sflewett** [comment]
That is true Daniel, I put the basischange part in only when I coded up the
3D case

Cheers

Sam
